name: release
on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run tests
        run: docker run --rm -v $PWD:/workdir gnuoctave/octave:8.4.0 make check
      - name: Build output
        run: make dist
      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{github.tag}}"
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: "build/*.tar.gz"
